/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CambioGuardiaRouteImport } from './routes/cambio-guardia'
import { Route as CompensatorioRouteImport } from './routes/compensatorio'
import { Route as ControlGuardiaRouteImport } from './routes/control-guardia'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as IngresoRouteImport } from './routes/ingreso'
import { Route as LaoRouteImport } from './routes/lao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CambioGuardiaRoute = CambioGuardiaRouteImport.update({
  id: '/cambio-guardia',
  path: '/cambio-guardia',
  getParentRoute: () => rootRouteImport,
} as any)
const CompensatorioRoute = CompensatorioRouteImport.update({
  id: '/compensatorio',
  path: '/compensatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlGuardiaRoute = ControlGuardiaRouteImport.update({
  id: '/control-guardia',
  path: '/control-guardia',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresoRoute = IngresoRouteImport.update({
  id: '/ingreso',
  path: '/ingreso',
  getParentRoute: () => rootRouteImport,
} as any)
const LaoRoute = LaoRouteImport.update({
  id: '/lao',
  path: '/lao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cambio-guardia': typeof CambioGuardiaRoute
  '/compensatorio': typeof CompensatorioRoute
  '/control-guardia': typeof ControlGuardiaRoute
  '/horarios': typeof HorariosRoute
  '/ingreso': typeof IngresoRoute
  '/lao': typeof LaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cambio-guardia': typeof CambioGuardiaRoute
  '/compensatorio': typeof CompensatorioRoute
  '/control-guardia': typeof ControlGuardiaRoute
  '/horarios': typeof HorariosRoute
  '/ingreso': typeof IngresoRoute
  '/lao': typeof LaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cambio-guardia': typeof CambioGuardiaRoute
  '/compensatorio': typeof CompensatorioRoute
  '/control-guardia': typeof ControlGuardiaRoute
  '/horarios': typeof HorariosRoute
  '/ingreso': typeof IngresoRoute
  '/lao': typeof LaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cambio-guardia'
    | '/compensatorio'
    | '/control-guardia'
    | '/horarios'
    | '/ingreso'
    | '/lao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cambio-guardia'
    | '/compensatorio'
    | '/control-guardia'
    | '/horarios'
    | '/ingreso'
    | '/lao'
  id:
    | '__root__'
    | '/'
    | '/cambio-guardia'
    | '/compensatorio'
    | '/control-guardia'
    | '/horarios'
    | '/ingreso'
    | '/lao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CambioGuardiaRoute: typeof CambioGuardiaRoute
  CompensatorioRoute: typeof CompensatorioRoute
  ControlGuardiaRoute: typeof ControlGuardiaRoute
  HorariosRoute: typeof HorariosRoute
  IngresoRoute: typeof IngresoRoute
  LaoRoute: typeof LaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambio-guardia': {
      id: '/cambio-guardia'
      path: '/cambio-guardia'
      fullPath: '/cambio-guardia'
      preLoaderRoute: typeof CambioGuardiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compensatorio': {
      id: '/compensatorio'
      path: '/compensatorio'
      fullPath: '/compensatorio'
      preLoaderRoute: typeof CompensatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-guardia': {
      id: '/control-guardia'
      path: '/control-guardia'
      fullPath: '/control-guardia'
      preLoaderRoute: typeof ControlGuardiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingreso': {
      id: '/ingreso'
      path: '/ingreso'
      fullPath: '/ingreso'
      preLoaderRoute: typeof IngresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lao': {
      id: '/lao'
      path: '/lao'
      fullPath: '/lao'
      preLoaderRoute: typeof LaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CambioGuardiaRoute: CambioGuardiaRoute,
  CompensatorioRoute: CompensatorioRoute,
  ControlGuardiaRoute: ControlGuardiaRoute,
  HorariosRoute: HorariosRoute,
  IngresoRoute: IngresoRoute,
  LaoRoute: LaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
